### ISSUE TITLE
Only one hit per ip

### ISSUE THREAD

**Issue by Kraymer** [brentvollebregt/hit-counter#1]
Re-requesting the same svg url with same ip should imo not increment the counter.

**Comment by brentvollebregt** [comment]
I have made it so when a client re-requests a page (which will request the hit counter again) within 1 minute (can be configured, the hosted site is currently set to 1min) of their last request, the counter will not be incremented.

My main thinking behind this is that if someone comes back to a page after a couple of days, the host-site will most likely want to count this as another hit. Currently I do feel that 1min is quite short and was intending on bumping up the default to something like 10mins.

The reason I have not used IP addresses and instead generate a cookie for each new visit is that people in places that have big networks (like universities) that use the same IP (or a lot of the same IPs) will not have each user counted for a view even though they are completely different people on different computers.

If you have reasoning around this decision, please say; I am always open to offers and a discussion of what is best.

**Comment by brentvollebregt** [comment]
Closing due to no further discussion on this topic. Feel free to leave opinions on a better way to handle this is you have one.
