### ISSUE TITLE
Counter is broken

### ISSUE THREAD

**Issue by singularityhacker** [brentvollebregt/hit-counter#18]
See: https://github.com/singularityhacker
It was working fine for several weeks but seems to have suddenly stopped.

**Comment by brentvollebregt** [comment]
How has it stopped? I've just tested it using your badge and it seems to be working fine.

**Comment by singularityhacker** [comment]
Very strange. It wasn't working most of yesterday and today but seems to be fine now. I'll try to get more detailed information if it stops working again instead of just saying "it's not working". Sorry for the false alarm.

**Comment by brentvollebregt** [comment]
Since you have this badge being rendered by GitHub, you might have thought that it's not working due to GitHub trying to cache the image.
