### ISSUE TITLE
hit-counter gives timeout

### ISSUE THREAD

**Issue by ArminJo** [brentvollebregt/hit-counter#19]
my hitcounters does not work. e.g. https://hitcounter.pythonanywhere.com/count/tag.svg?url=https://github.com/ArminJo/ServoEasing

**Comment by brentvollebregt** [comment]
The server has been witnessing a significant amount of traffic lately and for some reason the PythonAnywhere instance is definitely not performing like it used to despite many restarts. 

Are you able to reproduce this issue locally?

**Comment by brentvollebregt** [comment]
@ArminJo replied in #20 

> Ok locally it took more than 30 seconds to see the result, but Github waits only for a few seconds otherwise it displays the link text.
At refreshing my local test in Firefox I see now no result but.

When you say you tried it locally, did you run the server locally, or just request for something from the hosted project (non-local)?

**Comment by ArminJo** [comment]
After disabling the uBlock origin adblocker I can comment and update a comment.
**Sorry for the inconvenience!!!**

Her my answers:
Ok locally it took more than 30 seconds to see the result, but Github waits only for a few seconds otherwise it displays the link text.
At refreshing my local test in Firefox I see now no result but.

```
Something went wrong :-( 
This website is hosted by PythonAnywhere, an online hosting environment. 
Something went wrong while trying to load it; please try again later.
...
Error code: 502-backend
```

I have no server I just pasted the URL from above in my local Firefox browser.

**Comment by brentvollebregt** [comment]
I had asked

> Are you able to reproduce this issue locally?

When asking this, I meant if you run the server yourself (not using the hosted option) locally, do you get similar results? If so, then it is something wrong with the server otherwise it would most likely be an issue with the host (my assumption).

**Comment by brentvollebregt** [comment]
I have looked at the server logs and discovered a single domain is accountable for the majority of the traffic at the moment which is taking the server down. 
I have just introduced a blacklist and blocked the URL so hopefully, we should see improvement in the coming hours.

**Comment by ArminJo** [comment]
Thanks for your effort, but 
`https://hitcounter.pythonanywhere.com/count/tag.svg?url=https%3A%2F%2Fgithub.com%2Fukw100%2FIRMP`
still gives Error 502.

**Comment by brentvollebregt** [comment]
The domain accountable for the majority of the traffic I mentioned before has their own instance now so hopefully it's taken some strain off the server. The demo should be running a bit better now but I can't promise anything - it's just a demo.

If you want to report an issue with the application itself (which is what this repo is), I recommend reproducing it locally first otherwise I can't do much.

If you want an instance more reliable, there are [instructions in the docs on how to set your own instance up](https://github.com/brentvollebregt/hit-counter/blob/master/docs/setup.md#pythonanywhere-setup).

**Comment by ArminJo** [comment]
Thanks.
