### ISSUE TITLE
proxy not supported

### ISSUE THREAD

**Issue by 1049451037** [brentvollebregt/hit-counter#2]
Hi, this is a really good tool. But it seems that your domain does not support proxy visit?

![image](https://user-images.githubusercontent.com/15194939/63212857-ca6f4880-c13c-11e9-8786-777a77ff7779.png)

**Comment by brentvollebregt** [comment]
Are you able to visit [www.pythonanywhere.com](https://www.pythonanywhere.com/) but not [hitcounter.pythonanywhere.com](https://hitcounter.pythonanywhere.com/)?

**Comment by 1049451037** [comment]
www seems ok but hitcounter gets error under proxy.

**Comment by brentvollebregt** [comment]
Do you still get the error when going to the site in an incognito window? There is nothing in the source for the route `/` in relation to proxies or networking in general (e.g. IP addresses) so I feel this might be a client-side data problem (you can get this error from an unrelated problem sometimes).

**Comment by hrishikesh2003** [comment]
How should I find the hit ratio of different websites using hit counter Web page?

**Comment by brentvollebregt** [comment]
Hit ratio? Could you please explain specifically what you mean by the hit ratio? Also, how does this relate to proxy issues?

**Comment by brentvollebregt** [comment]
Closing this issue due to no response for a significant amount of time.
