### ISSUE TITLE
Your issue setting may be wrong.

### ISSUE THREAD

**Issue by ArminJo** [brentvollebregt/hit-counter#21]
I again cannot comment in #19 and #20
I have no server I just pasted the URL from above in my local Firefox browser.

**Comment by brentvollebregt** [comment]
I'm pretty sure there is no "setting" that I could enable to stop you from commenting and editing your replies and if there is, I am not aware of it. 

In very recent issues people have replied without issue, maybe it is a temporary GitHub issue. 

Please stop creating new issues as replies - it makes it significantly difficult to keep track of the replies.
