### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by bluprince13** [brentvollebregt/hit-counter#23]
My requests started getting blocked from today.

```Access to fetch at 'https://hitcounter.pythonanywhere.com/count?url=https%3A%2F%2Fwww.bluprince13.com%2Fblog%2Fchanging-careers-from-aerospace-engineering-to-web-development%2F' from origin 'https://www.bluprince13.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.```

This is my code:

```
    const query = `?url=${encodeURIComponent(url)}`
    const path = `https://hitcounter.pythonanywhere.com/count${query}`
    const response = await fetch(path, {
        method: 'GET'
    })
    const hitCount = await response.json()
```

**Comment by brentvollebregt** [comment]
Which browser are you using?

**Comment by bluprince13** [comment]
I think the server was down maybe. I don’t have the issue anymore.

I tried multiple browsers.
