### ISSUE TITLE
The site is down

### ISSUE THREAD

**Issue by IamSreeman** [brentvollebregt/hit-counter#24]
https://hitcounter.pythonanywhere.com/ is down. Please look into it.

**Comment by brentvollebregt** [comment]
Seems to be working for me currently

**Comment by IamSreeman** [comment]
Now it is working sometimes and not working sometimes. The svg's also don't load if the site doesn't.
![Capture](https://user-images.githubusercontent.com/62174391/98910256-d7532700-24ba-11eb-86d3-f7be8be06216.JPG)
Here is the image. Maybe it is due to my location.

**Comment by hvoss49** [comment]
Works for me, but takes more than 10 second to load (macOS and Firefox)

**Comment by iamsreeman** [comment]
Now it's working fine close this issue.

**Comment by IamSreeman** [comment]
Now it's working fine.

**Comment by brentvollebregt** [comment]
For any others that run into this: the site at https://hitcounter.pythonanywhere.com/ is only a demo instance and if you want something reliable, you will need to host the project yourself.
