### ISSUE TITLE
Bug : Not Working (Doesn't Show up )

### ISSUE THREAD

**Issue by khanfarhan10** [brentvollebregt/hit-counter#28]
It shows :::
Error Fetching Resource 
For my repo count at https://github.com/khanfarhan10/TextSentimentAnalysis

**Comment by brentvollebregt** [comment]
I have the following in the README:

> Please note this is only a demo instance and any traffic that causes harm to the server will be blocked. Also due to how this demo instance is being hosted and the large amount of traffic it gets, the server does fall over some times.

It looks like you are using the demo instance which unfortunately goes down every so often. At the moment it is running.
