### ISSUE TITLE
Thankyou! Such a cool idea!

### ISSUE THREAD

**Issue by benwinding** [brentvollebregt/hit-counter#3]
So I had pretty much this exact idea a few months ago, and am glad I didn't try to implement it (yours is much better). I was going to try to dynamically create PNGs (which is much sillier and harder than SVGs), and I didn't think of using an anti-refresh system too!

Just wanted to thank you for creating this :ok_hand:

**Comment by brentvollebregt** [comment]
I'm glad you found the project useful! In terms of PNGs, PIL could accomplish it but SVGs are so much easier.
