### ISSUE TITLE
hit counter url is barely responsive

### ISSUE THREAD

**Issue by Yarboa** [brentvollebregt/hit-counter#30]
https://hitcounter.pythonanywhere.com response time is very slow, some time it returns something went wrong message

**Comment by brentvollebregt** [comment]
In the README I have put the note:

> Please note this is only a demo instance and any traffic that causes harm to the server will be blocked. Also due to how this demo instance is being hosted and the large amount of traffic it gets, the server does fall over some times.

Unfortunately, the tier this demo server is on cannot handle the significant amount of traffic it gets every day. Pulling the database locally and running the server locally does not show any issues, so I have to assume it is the host.

I recommend if you want to use this tool, host it yourself as https://hitcounter.pythonanywhere.com is only a demo instance.

I will look into some of the domains that are hitting this instance waaaaay to much and potentially start blocking them. I have just taken a sample of the last ~8800 calls to the server and more than half of the calls were from 8 domains which is a real shame for everyone trying this out.

**Comment by Yarboa** [comment]
Appreciate, you response, performance is excellent, kudos
