### ISSUE TITLE
Deprecated Usage Examples

### ISSUE THREAD

**Issue by j0hax** [brentvollebregt/hit-counter#31]
When copying and pasting the javascript demo code for [Getting the Count Raw](https://github.com/brentvollebregt/hit-counter#getting-the-count-raw) my browser gives following warning in the console:

>[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

I think updating the example to use asynchronous JS would be good long-term.

**Comment by brentvollebregt** [comment]
Took a bit longer than I would hope but that should do!

Thanks for reporting this 👌
