### ISSUE TITLE
Is the same person viewing the repo again and again counted as another view?

### ISSUE THREAD

**Issue by khanfarhan10** [brentvollebregt/hit-counter#32]

**Comment by brentvollebregt** [comment]
Does the documentation cover this: [https://github.com/brentvollebregt/hit-counter/blob/master/docs/background.md#anti-refresh-counting-system](https://github.com/brentvollebregt/hit-counter/blob/master/docs/background.md#anti-refresh-counting-system)?

**Comment by brentvollebregt** [comment]
Feel free to ask any more questions related to this if you have any

**Comment by khanfarhan10** [comment]
well that was too intimidating and complex. Is there a simpler binary (Yes/No) answer to this? @brentvollebregt ?

**Comment by brentvollebregt** [comment]
No. 

There is more I would need to ask to answer your question properly but if all you want a binary answer, there it is. I am assuming a lot to answer your question with a binary answer.

**Comment by khanfarhan10** [comment]
Thanks a lot.
