### ISSUE TITLE
How does counting for another site work?

### ISSUE THREAD

**Issue by King-of-Infinite-Space** [brentvollebregt/hit-counter#33]
Thanks for this nice project. I'm just a little confused regarding "Getting a Count For a Site That Isn't Me". I want to count the visit for a github.io page, but display the count in the corresponding repo. Do I need to include any code in the webpage for it to be counted? If not, how does the counting server know about visits to that page?

**Comment by brentvollebregt** [comment]
You will still need to put the image or call the endpoint on the target page.
Without this, we wouldn't be able to track the visits (like you are questioning).
