### ISSUE TITLE
Appears to be down

### ISSUE THREAD

**Issue by jagoosw** [brentvollebregt/hit-counter#34]
Hi,

Your website appears to be down https://www.isitdownrightnow.com/hitcounter.pythonanywhere.com.html

Let me know if there's anything I can do to help you fix.

Jago

**Comment by brentvollebregt** [comment]
See #30 and #28

I have the following in the README:

> Please note this is only a demo instance and any traffic that causes harm to the server will be blocked. Also due to how this demo instance is being hosted and the large amount of traffic it gets, the server does fall over some times.

It looks like you are using the demo instance which unfortunately goes down every so often. At the moment it is running.
