### ISSUE TITLE
Feature request: unique visitor count

### ISSUE THREAD

**Issue by hurutta** [brentvollebregt/hit-counter#36]
Hi,
It would be really great if there's a feature of getting total count of unique visitors. If unique visitor by username of github is not possible, what about counting unique visitor by IP-address or anything else maybe? (I think it's possible, I found some sites provide this feature by image, couldn't find any which provide SVG).

**Comment by brentvollebregt** [comment]
I would rather not track individual users - that seems a bit invasive for a basic tag.

Also, it might get the project in a bit of trouble if we don't account for the EU's GDPR.

**Comment by hurutta** [comment]
got it, closing the issue then.
