### ISSUE TITLE
Count starts with 733 instead of 1

### ISSUE THREAD

**Issue by ArminJo** [brentvollebregt/hit-counter#4]
Hi,
Thanks for this very cool tool, I included it in all my repos.

I just inserted the markup for your hit counter in my repo https://github.com/ArminJo/Smart-Battery-Module-Info_For_Arduino , but for this repo it did not start with 1 but starts with 733!
This is the included markup:
[![Hit Counter](https://hitcounter.pythonanywhere.com/count/tag.svg?url=https%3A%2F%2Fgithub.com%2FArminJo%2FSmart-Battery-Module-Info_For_Arduino)](https://github.com/brentvollebregt/hit-counter)

How can I reset the counter?

Thanks in advance
Armin

**Comment by brentvollebregt** [comment]
Are you 100% sure it started with 733 and not that you (or someone else) has made requests for that URL before? [In the source, I start all entries at 0](https://github.com/brentvollebregt/hit-counter/blob/master/db.py#L37).

**Comment by ArminJo** [comment]
Hi Brent I am 110% sure, since I did this in the same time 3 times with other repos and they all started with 1.
Is there a possibility to reset the counter?

**Comment by ArminJo** [comment]
Ok ok,
I lost overview, and introduced the counter weeks before, but did not notice it :-(
Sorry for my mistake, and thanks for your great work to provide this cool tool.
Armin
