### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by hvoss49** [brentvollebregt/hit-counter#5]
I am pretty new to Python and do not really understand where to put the files. I want to use it at my own server, let's say: www.example.com
The web files are saved in /var/www/html/myExample/   where myExample is the root directory
of example.com. I have the python files in this directory, too and can successfully start the server.py 
I put your template index.html into /var/www/html/myExample/ but I suppose that is not enough??

**Comment by brentvollebregt** [comment]
What are you wanting to do, host the server or just show the badge?

**Comment by hvoss49** [comment]
Show the badge.

**Comment by brentvollebregt** [comment]
In the README I describe that all you need to do is add the img tag: 

```html 
<img src="https://hitcounter.pythonanywhere.com/count/tag.svg" alt="Hits">
```

**Comment by hvoss49** [comment]
True and that works. But I thought, that I can save bandwidth if I use an
own
server. Not?


Brent Vollebregt <notifications@github.com> schrieb am Mo. 27. Apr. 2020 um
22:33:

**Comment by brentvollebregt** [comment]
I host it publicly for others to use if they wish; you can see a lot of people use it aside from me on the [home page](https://hitcounter.pythonanywhere.com/).

If you wish to host it yourself, the instructions are outlined in the [README under "Hosting Your Own Server"](https://github.com/brentvollebregt/hit-counter#hosting-your-own-server).

**Comment by hvoss49** [comment]
Sorry, but I do not want it to be hosted on pythonanywhere.com, but on my own server.

**Comment by brentvollebregt** [comment]
Then you can follow the instructions I linked above to run your own instance.
