### ISSUE TITLE
OperationError: database is locked

### ISSUE THREAD

**Issue by ourworldtech** [brentvollebregt/hit-counter#6]
I hosted on PythonAnywhere and the database is locked sometimes. I saw that in the Error log. How to prevent this?

**Comment by brentvollebregt** [comment]
I've just looked at my error logs and have nothing like this - I'm currently on 1b9b2792111a740d3f299d98c9ca7a5410ee1b87.

I'm going to give it a good guess and say you aren't running the latest on master? I fixed an issue like this back in December - 106c441c15c5403389bb93a072cc6ecbc525dde1 (6 months ago). 

Are you using the most recent version?

**Comment by ourworldtech** [comment]
Got it. Thank you.
